stages:
  - test
  - docker_build
  - push_docker_image
test:
  image: python:2.7
  stage: test
  script:
    - make deps
    - make lint
    - make test
    - make test_xunit
    - make test_robot
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
    - apk add --update make
    - make docker_build
    - make docker_push
