stages:
  - test
  - docker_build
  - push_docker_image
test:
  image: python:2.7
  stage: test
  script:
    - make deps
    - make lint
    - make test
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
    - apk add --update make
    - make docker_build
    - make docker_push
  stage: push_docker_image
  script:
    - docker build -t registry.gitlab.com/krisbalko/se_hello_printer_app .
    - docker push registry.gitlab.com/krisbalko/se_hello_printer_app
